// AUTO-GENERATED by scripts/emit-core-stamp.ts (npm run core:wasm) — do not edit.
// The crate-source hash the committed .wasm was built from (gate G5).
export const CORE_SOURCE_HASH = "fdbb3c67aee05008";
