/**
 * Stamp the committed wasm package with the crate-source hash it was built from (Track F3,
 * gate G5). Run by `npm run core:wasm` AFTER wasm-pack; `src/game/coreVersion.test.ts`
 * recomputes the hash and fails on mismatch, so a crate edit without a rebuild can't ship.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { currentCoreVersion } from './coreVersion';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const version = currentCoreVersion();
writeFileSync(
  join(ROOT, 'src/game/core-pkg/core.version.ts'),
  `// AUTO-GENERATED by scripts/emit-core-stamp.ts (npm run core:wasm) — do not edit.\n` +
    `// The crate-source hash the committed .wasm was built from (gate G5).\n` +
    `export const CORE_SOURCE_HASH = ${JSON.stringify(version)};\n`,
);
console.log(`stamped core-pkg with crate hash ${version}`);
