/**
 * Turn a Rust bake's output directory (`bake --out DIR`: levels.json + provenance.json) into
 * the committed modules — the F2-decided emission path, live as of the F4 cutover: Rust emits
 * JSON only, this script writes `src/game/levels.data.ts`, `src/game/levels.meta.ts`, and
 * `scripts/levels.provenance.json` (then `emit-provenance.ts` / `archive-report.ts` run as
 * before). Wired into `npm run build:levels`. (The JS bake it replaced was deleted in F5.)
 *
 * Version stamp: the committed data carries the crate-source hash (`currentGeneratorVersion()`
 * delegates to `coreVersion` since F5), so ONE hash stamps both committed artifacts — the boards
 * here (`baked.test.ts`) and the `.wasm` (G5 `coreVersion.test.ts`).
 *
 * Prints whether the boards byte-match the currently committed data — at cutover they MUST
 * (the Rust bake is byte-identical); after a future intentional rule change they won't.
 *
 * Usage: npx tsx scripts/emit-baked-from-rust.ts <bake-out-dir>
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { currentGeneratorVersion } from './levelVersion';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = process.argv[2];
if (!dir) {
  console.error('usage: npx tsx scripts/emit-baked-from-rust.ts <bake-out-dir>');
  process.exit(2);
}

const baked = JSON.parse(readFileSync(join(dir, 'levels.json'), 'utf8')) as { level: number }[];
const provenance = JSON.parse(readFileSync(join(dir, 'provenance.json'), 'utf8')) as {
  count: number;
  perShape: number;
  levels: unknown[];
};
const version = currentGeneratorVersion();

// Cutover sanity: compare the new board data against what's currently committed.
const dataPath = join(ROOT, 'src/game/levels.data.ts');
const body = JSON.stringify(baked);
if (existsSync(dataPath)) {
  const committed = readFileSync(dataPath, 'utf8');
  const match = committed.includes(`export const BAKED_LEVELS = ${body} `);
  console.log(
    match
      ? 'boards byte-match the committed levels.data.ts (expected at cutover / no-op re-bakes)'
      : 'boards DIFFER from the committed levels.data.ts (expected only after an intentional rule change)',
  );
}

writeFileSync(
  join(ROOT, 'src/game/levels.meta.ts'),
  `// AUTO-GENERATED by scripts/emit-baked-from-rust.ts — do not edit by hand. Run \`npm run build:levels\`.\n` +
    `export const GENERATOR_VERSION = ${JSON.stringify(version)};\n`,
);
writeFileSync(
  dataPath,
  `/* eslint-disable */\n` +
    `// AUTO-GENERATED by scripts/emit-baked-from-rust.ts (Rust bake) — do not edit by hand. Run \`npm run build:levels\`.\n` +
    `import type { BakedLevel } from './baked';\n\n` +
    `export const BAKED_LEVELS = ${body} as readonly BakedLevel[];\n`,
);
writeFileSync(
  join(ROOT, 'scripts/levels.provenance.json'),
  JSON.stringify(
    { version, count: provenance.count, perShape: provenance.perShape, levels: provenance.levels },
    null,
    2,
  ) + '\n',
);

console.log(`emitted ${baked.length} levels (version ${version}) from ${dir}`);
