/**
 * Emit the DEV-only `src/game/levels.provenance.ts` module from the committed bake sidecar
 * `scripts/levels.provenance.json`. Kept SEPARATE from `build-levels.ts` on purpose: that file is in
 * the `levelVersion.ts` staleness hash, so adding an output write there would force a full re-bake.
 * This reader-only step depends on nothing the bake hashes, so it can regenerate the provenance module
 * (e.g. after a curve change re-runs the bake, or to bootstrap from an existing JSON) without touching
 * the baked boards. Wired to run after the bake in the `build:levels` npm script, and runnable alone via
 * `npm run levels:provenance`.
 *
 * The output is a tree-shakeable record the in-app Level Inspector imports only under
 * `import.meta.env.DEV` (see `src/game/provenance.ts`), so it never ships to production.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

interface ProvenanceRow {
  level: number;
}

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'scripts/levels.provenance.json');
const OUT = join(ROOT, 'src/game/levels.provenance.ts');

const json = JSON.parse(readFileSync(SRC, 'utf8')) as { levels: ProvenanceRow[] };
const byLevel: Record<number, ProvenanceRow> = {};
for (const row of json.levels) byLevel[row.level] = row;

writeFileSync(
  OUT,
  `/* eslint-disable */\n` +
    `// AUTO-GENERATED by scripts/emit-provenance.ts from scripts/levels.provenance.json — do not edit by hand.\n` +
    `// DEV-ONLY difficulty provenance for the in-app Level Inspector (Track E1). Never imported in production.\n` +
    `import type { LevelProvenance } from './provenance';\n\n` +
    `export const LEVEL_PROVENANCE: Record<number, LevelProvenance> = ${JSON.stringify(byLevel)};\n`,
);

console.log(`Wrote src/game/levels.provenance.ts (${json.levels.length} levels) from provenance JSON.`);
